#!/usr/bin/env bash

set -e

uid=${UID:-0}
gid=${GID:-0}

[[ $(stat -c "%u" /data) != $UID ]] && chown -R $uid:$gid /data

[ "$1" = "steamcmd-run" ] && exec gosu $uid:$gid "$@"
exec gosu $uid:$uid steamcmd-env "$@"
