#!/usr/bin/env bash

umask 0002
chmod g+w /data

if [ $(id -u) = 0 ]; then
  if [[ -v UID && $UID != $(id -u) ]]; then
    usermod -u $UID steam
  fi

  if [[ -v GID ]]; then
    groupmod -o -g $GID steam
  fi

  if [[ $(stat -c "%u" /data) != $UID ]]; then
    chown -R steam:steam /data
  fi

  if [ "$1" = "steamcmd-run" ]; then
    exec gosu steam:steam "$@"
  else
    exec gosu steam:steam steamcmd-env "$@"
  fi
else
  exec steamcmd-env "$@"
fi