#!/usr/bin/env bash

set -e

if [ -z "$STEAMCMD_SKIP_UPDATE" ]; then
  app_dir=${STEAMCMD_APP_DIR:-/data}
  login=${STEAMCMD_LOGIN:-anonymous}

  if [ -z "$STEAMCMD_APP_ID" ]; then
    echo "ERROR: STEAMCMD_APP_ID is required"
    exit 1
  fi

  [ -z "$STEAMCMD_NO_VALIDATE" ]   && validate="validate"
  [ -n "$STEAMCMD_BETA" ]          && beta="-beta $STEAMCMD_BETA"
  [ -n "$STEAMCMD_BETA_PASSWORD" ] && betapassword="-betapassword $STEAMCMD_BETA_PASSWORD"

  steamcmd +login $login \
    +force_install_dir $app_dir \
    +app_update $STEAMCMD_APP_ID $beta $betapassword $validate \
    +quit
fi

steamcmd-env "$@"